# Generated by Django 3.1.5 on 2021-01-12 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=30, unique=True)),
                ('certificate_id', models.CharField(max_length=30)),
                ('municipality', models.IntegerField()),
                ('building', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('heat_efficiency_lvl', models.CharField(max_length=5)),
                ('date_stored', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
    ]
