# Generated by Django 3.1.5 on 2021-01-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvio_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energycertificate',
            name='heat_efficiency_lvl',
            field=models.CharField(max_length=4),
        ),
    ]
